config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    member do
      get 'history'
      get 'rent', to: 'products#prerent'
      post 'rent', to: 'products#postrent'
      get 'return', to: 'products#prereturn'
      post 'return', to: 'products#postreturn'
    end
    collection do
      get 'search'
    end
  end

  resources :users
  
  get 'new_transaction' => 'transactions#new'
  post 'new_transaction' => 'transactions#create'
  get 'transactions/:id' => 'transactions#show'
  get 'products/:id/new' => 'transactions#initiate', as: :initiate_transaction
  post 'products/:id' => 'transactions#submit', as: :submit_transaction
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'transactions#new'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :transactions, dependent: :destroy
  validates :ic, presence: true
end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :product
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
            
  has_secure_password
  validates :password, length: { minimum: 6 }, on: :create
  # isAdmin is false by default now!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :loggedIn
  before_action :set_one, only: [:show, :edit, :update, :destroy, :history, :prerent, :postrent, :prereturn, :postreturn]
  before_action :set_all, only: [:index]
  
  def index
  end
  
  def show
    @transactions = @product.transactions
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(post_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end

  def history
  end

  def prerent
  end

  def postrent
  end

  def prereturn
  end

  def postreturn
  end

  private
  
    def loggedIn
      @user = User.find_by(id: session[:user_id])
      if @user.nil?
        redirect_to login_url
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_one
      @product = Product.find(params[:id])
      @trans = Transaction.where(product_id: @product.id)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_all
      @products = Product.all
      @num_products = @products.nil? ? 0 : @products.size()
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:product).permit(:ic,:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      user = User.find(session[:user_id])
      redirect_to user
    end
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = 'Success!'
      log_in user
      redirect_to root_path
    else
      # Error message
      redirect_to login_url, :alert => "Invalid email/password combination"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to login_url, :notice => "Logged Out"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :loggedIn
  
  def search
  end
  
  def index
  end
  
  def initiate
    @transaction = Transaction.new
    @product = Product.find(params[:id])
  end
  
  def submit
    product_id = params[:id]
    ttype = params[:transaction][:transtype] # transaction type always shows as 0
    image = params[:transaction][:image]
    
    @product = Product.find(product_id)
    @transaction = Transaction.new
    @transaction.product_id = product_id
    @transaction.transtype = ttype
    @transaction.image = image
    
    if @transaction.save
        redirect_to @product, :notice => "Transaction Saved"
      else
        redirect_to root_path
    end
    
  end
  
  def show
    @transaction = Transaction.find(params[:id])
    @ic = @transaction.product.ic
    @pics = @transaction.image
  end
  
  def new
   @product = Product.new
  end
  
  def create
    @ic = params[:product][:ic]
    @product = Product.find_by(ic: @ic)
    if !@product.nil?
      redirect_to @product
    else
      redirect_to new_product_path, :alert => "Equipment with given IC# does not exist. Please create new Equipment below."
    end
  end
  
  private
  
  def loggedIn
      @user = User.find_by(id: session[:user_id])
      if @user.nil?
        redirect_to login_url
      end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :loggedIn
  # before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      puts params
      @user = User.find(params[:session][:id])
    end
    
    def loggedIn
      @user = User.find_by(id: session[:user_id])
      if @user.nil?
        redirect_to login_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Hertz Pictures"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def all_products
    @all_products ||= Product.all
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.fgcu.edu">Hertz Rental Equipment Electronic Storage</a>
    by <a href="#">Team 3 - Rabeet Fatmi, Lloyd Gibson, Brent Oliver, Stefan Oswald.</a>
  </small>
  <nav>
    <ul>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
    <%= link_to image_tag("https://images.hertz.com/rac/misc/refresh09/hertz-car-rental-logo.png"), root_path, id: "logo" %>
    <nav>
      <ul class="nav nav-tabs">
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to "New Transaction",   new_transaction_path %></li>
        <li><%= link_to "Equipments List",   products_path %></li>
        <li><%= link_to "Log out", logout_path, method: "delete", class: "nav navbar-right" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_products_list.html.erb
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>IC #</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% all_products.each do |a| %>
          <tr>
            <% if a.ic %>
              <td><%= a.ic %></td>
            <% else %>
              <td>Product <%= a.id %></td>
            <% end %>
            <td></td>
            <td><%= link_to 'View', a, class: 'btn btn-xs btn-default' %>
            <%= link_to "Edit", edit_product_path( a ), class: 'btn btn-xs btn-success' %>
            <%= link_to 'Destroy', a, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if logged_in? %>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  <% else %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  <% end %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ic %><br>
    <%= f.text_field :ic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/create.json.erb
{
  <% if @success == 1 %>
  success=true,
  id=<%= @product.id %>,
  ic_num=<%= @product.ic %>,
  name="<%= @product.name %>"
  <% else %>
  success=false,
  message="<%= @message %>"
  <% end %>
}

app/views/products/history.html.erb
<h1>Products#history</h1>
<p>Find me in app/views/products/history.html.erb</p>

app/views/products/history.json.erb
<h1>Products#history</h1>
<p>Find me in app/views/products/history.html.erb</p>

app/views/products/index.html.erb
<% provide(:title, "Listing Products") %>

<%= render 'layouts/products_list' %>

<%= link_to 'New Equipment', new_product_path %>

app/views/products/index.json.erb
{
  num_pruducts=<%= @num_products %>,
  products=[
  <% i = 0 %>
  <% @products.each do |product| %>
    <%= i == 0 ? "" : ", " %>
    {
      id=<%= product.id %>,
      ic_num=<%= product.ic %>,
      name="<%= product.name %>"
    }
  <% end %>
  ]
}

app/views/products/postrent.json.erb
<h1>Products#rent</h1>
<p>Find me in app/views/products/rent.html.erb</p>

app/views/products/postreturn.html.erb
<h1>Products#return</h1>
<p>Find me in app/views/products/return.html.erb</p>

app/views/products/postreturn.json.erb
<h1>Products#return</h1>
<p>Find me in app/views/products/return.html.erb</p>

app/views/products/prerent.html.erb
<h1>Products#prerent</h1>
<p>Find me in app/views/products/prerent.html.erb</p>

app/views/products/prereturn.html.erb
<h1>Products#prereturn</h1>
<p>Find me in app/views/products/prereturn.html.erb</p>

app/views/products/show.html.erb
<h1>Equipment IC# <%= @product.ic %></h1>

<p id="notice"><%= notice %></p>

<%= link_to 'Initiate Transaction', initiate_transaction_path, class: 'btn btn-large btn-success' %>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Past Transactions History</th>
          <th>Date Created</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @transactions.each do |a| %>
          <tr>
            <% if a.transtype.nil? %>
              <td><%= "Transaction type N/A"  %></td>
            <% else %>
              <td><%= a.transtype %></td>
            <% end %>
            <td><%= a.created_at %></td>
            <td><%= link_to 'View', '/transactions/'+a.id.to_s, class: 'btn btn-xs btn-default' %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= link_to 'Initiate Transaction', initiate_transaction_path, class: 'btn btn-large btn-success' %>

app/views/products/show.json.erb
{
  id=<%= @product.id %>,
  ic_num=<%= @product.ic %>,
  name="<%= @product.name %>"
}

app/views/products/update.json.erb
{
  <% if @success == 1 %>
  success=true,
  id=<%= @product.id %>,
  old_ic_num=<%= @old_ic %>,
  old_name="<%= @old_name %>",
  ic_num=<%= @product.ic %>,
  name="<%= @product.name %>"
  <% else %>
  success=false,
  message="<%= @message %>"
  <% end %>
}

app/views/transactions/create.html.erb
Received IC Number: <%= @ic %>

app/views/transactions/initiate.html.erb
<%= form_for(@transaction, :html => {:multipart => true}, url: submit_transaction_path) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Transaction_Type %><br>
    <%= f.collection_select :transtype, Provider.order(:name), :name, :name, include_blank: false %>
  </div>
  
  <div class="field">
    <%= f.label :Images %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/new.html.erb
<% provide(:title, "Web Portal") %>

<h1>New Transaction</h1>
<h2>Please enter an IC number</h2>
<%= form_for(@product, url: new_transaction_path) do |f| %>
    <%= f.label :IC_Number %>
    <%= f.text_field :ic, class: 'form-control' %><br>
    <center>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </center><br>
<% end %>

app/views/transactions/show.html.erb
<h1>Viewing Transaction</h1>
<h3>IC#: <%= @ic  %> - <%= @transaction.transtype %></h3>
<%= image_tag @transaction.image_url(:thumb).to_s %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, "Web Portal") %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-12">
    <h3>Welcome <%= @user.name %></h3>
  </div>
</div>
<div class="row">
  <%= render 'layouts/user' %>
</div>